### ISSUE TITLE
it's report erro when run qv2ray-2.6.3-25 :qv2ray: error while loading shared libraries: libgrpc++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Qv2ray/Qv2ray#1523]
qv2ray: error while loading shared libraries: libgrpc++.so.1: cannot open shared object file: No such file or directory

**Comment by cubercsl** [comment]
see also https://github.com/Qv2ray/Qv2ray/issues/1494

**Comment by lunasama1** [comment]
i also meet this problem how can i solve it?

**Comment by cubercsl** [comment]
@lunasama1 Use qv2ray-dev-git instead.

**Comment by lunasama1** [comment]
i use yay -s to download but it said can't load qvssrplugin.v2.0.3.linux-x64.so

**Comment by lunasama1** [comment]
if i don't replace it ,can it be solved by  update?

**Comment by cubercsl** [comment]
> if i don't replace it ,can it be solved by update?

If you use `qv2ray-dev-git`, you should also use plugin in dev branch, such as `qv2ray-plugin-ssr-dev-git`.

`qv2ray` should be fixed and you can download in archlinuxcn now. https://repo.archlinuxcn.org/x86_64/qv2ray-2.6.3-27-x86_64.pkg.tar.zst

**Comment by lunasama1** [comment]
I think i don't know dev branch well, but i solve it by update.Thank you!

**Comment by glyh** [comment]
I use qv2ray-dev-git, but the problem still exists, how can I solve it?

**Comment by cubercsl** [comment]
@glyh if you build from aur, just rebuild it.
